"""initial schema

Revision ID: ba4595389395
Revises: 
Create Date: 2026-02-13 11:12:08.358299+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba4595389395'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('old_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=True),
    sa.Column('risk_profile', sa.String(), nullable=True),
    sa.Column('total_assets', sa.Float(), server_default='0', nullable=False),
    sa.Column('kyc_expiry_date', sa.Date(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('aadhar_number', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('source_of_wealth', sa.String(), nullable=True),
    sa.Column('investment_experience', sa.String(), nullable=True),
    sa.Column('preferred_communication', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('communication_campaigns',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delivered_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('opened_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_campaigns_id'), 'communication_campaigns', ['id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('dividend_amount', sa.Float(), nullable=True),
    sa.Column('ratio', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='announced', nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_id'), 'corporate_actions', ['id'], unique=False)
    op.create_table('message_templates',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_id'), 'message_templates', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='wealth_advisor', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('advice_records',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('advice_type', sa.String(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('risk_considerations', sa.Text(), nullable=True),
    sa.Column('client_acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advice_records_id'), 'advice_records', ['id'], unique=False)
    op.create_table('ai_meeting_summaries',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_discussion_points', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('action_items', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('decisions_made', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('next_steps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('risks_discussed', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('tasks_created', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_meeting_summaries_id'), 'ai_meeting_summaries', ['id'], unique=False)
    op.create_table('campaign_message_logs',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['communication_campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_message_logs_id'), 'campaign_message_logs', ['id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['communication_campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_recipients_id'), 'campaign_recipients', ['id'], unique=False)
    op.create_table('campaign_segments',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filter_criteria', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('client_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_auto_updating', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['communication_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_segments_id'), 'campaign_segments', ['id'], unique=False)
    op.create_table('cash_balances',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('available_cash', sa.Float(), server_default='0', nullable=False),
    sa.Column('pending_cash', sa.Float(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_balances_advisor_id'), 'cash_balances', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_cash_balances_client_id'), 'cash_balances', ['client_id'], unique=True)
    op.create_index(op.f('ix_cash_balances_id'), 'cash_balances', ['id'], unique=False)
    op.create_table('churn_predictions',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('churn_risk_percentage', sa.Float(), nullable=True),
    sa.Column('risk_factors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_churn_predictions_id'), 'churn_predictions', ['id'], unique=False)
    op.create_table('client_activities',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_activities_id'), 'client_activities', ['id'], unique=False)
    op.create_table('client_aum',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('current_aum', sa.Float(), server_default='0', nullable=False),
    sa.Column('equity_aum', sa.Float(), server_default='0', nullable=False),
    sa.Column('debt_aum', sa.Float(), server_default='0', nullable=False),
    sa.Column('hybrid_aum', sa.Float(), server_default='0', nullable=False),
    sa.Column('other_assets', sa.Float(), server_default='0', nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_aum_id'), 'client_aum', ['id'], unique=False)
    op.create_table('client_consents',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_consents_id'), 'client_consents', ['id'], unique=False)
    op.create_table('client_corporate_actions',
    sa.Column('corporate_action_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('holdings_quantity', sa.Float(), nullable=True),
    sa.Column('estimated_impact', sa.Float(), nullable=True),
    sa.Column('ai_personalized_summary', sa.Text(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['corporate_action_id'], ['corporate_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_corporate_actions_id'), 'client_corporate_actions', ['id'], unique=False)
    op.create_table('client_documents',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_documents_id'), 'client_documents', ['id'], unique=False)
    op.create_table('client_engagement_scores',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('engagement_level', sa.String(), nullable=True),
    sa.Column('login_frequency', sa.Integer(), server_default='0', nullable=False),
    sa.Column('campaign_response_rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('days_since_last_interaction', sa.Integer(), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_engagement_scores_id'), 'client_engagement_scores', ['id'], unique=False)
    op.create_table('client_family_members',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_nominee', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_family_members_id'), 'client_family_members', ['id'], unique=False)
    op.create_table('client_life_goals',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('current_amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('monthly_sip', sa.Float(), server_default='0', nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_life_goals_id'), 'client_life_goals', ['id'], unique=False)
    op.create_table('client_nominees',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('id_proof_type', sa.String(), nullable=True),
    sa.Column('id_proof_number', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_nominees_id'), 'client_nominees', ['id'], unique=False)
    op.create_table('client_notes',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_notes_id'), 'client_notes', ['id'], unique=False)
    op.create_table('client_reminders',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recurrence_interval', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_reminders_id'), 'client_reminders', ['id'], unique=False)
    op.create_table('client_tags',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_tags_id'), 'client_tags', ['id'], unique=False)
    op.create_table('commission_records',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('upfront_commission', sa.Float(), server_default='0', nullable=False),
    sa.Column('trail_commission', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_commission', sa.Float(), server_default='0', nullable=False),
    sa.Column('commission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_records_id'), 'commission_records', ['id'], unique=False)
    op.create_table('communication_logs',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('communication_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='sent', nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_id'), 'communication_logs', ['id'], unique=False)
    op.create_table('compliance_alerts',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), server_default='medium', nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_alerts_id'), 'compliance_alerts', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('corporate_action_alerts',
    sa.Column('corporate_action_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), server_default='info', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporate_action_id'], ['corporate_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_action_alerts_id'), 'corporate_action_alerts', ['id'], unique=False)
    op.create_table('funding_accounts',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_accounts_advisor_id'), 'funding_accounts', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_funding_accounts_client_id'), 'funding_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_funding_accounts_id'), 'funding_accounts', ['id'], unique=False)
    op.create_table('funding_requests',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('funding_type', sa.String(length=50), nullable=False),
    sa.Column('workflow_stage', sa.String(length=50), server_default='initiated', nullable=False),
    sa.Column('source_account', sa.String(length=100), nullable=True),
    sa.Column('destination_account', sa.String(length=100), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('stage_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_requests_advisor_id'), 'funding_requests', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_funding_requests_client_id'), 'funding_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_funding_requests_funding_type'), 'funding_requests', ['funding_type'], unique=False)
    op.create_index(op.f('ix_funding_requests_id'), 'funding_requests', ['id'], unique=False)
    op.create_index(op.f('ix_funding_requests_workflow_stage'), 'funding_requests', ['workflow_stage'], unique=False)
    op.create_table('invoices',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_advisor_id'), 'invoices', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), server_default='new', nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_client_id', sa.UUID(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('security_name', sa.String(length=255), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='buy, sell, switch'),
    sa.Column('execution_type', sa.String(length=20), server_default='market', nullable=False, comment='market, limit, stop_loss, amo'),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False, comment='pending, approved, executed, cancelled, rejected, partially_executed'),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_advisor_id'), 'orders', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_type'), 'orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('payments',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_advisor_id'), 'payments', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_reference_number'), 'payments', ['reference_number'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payout_requests',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payout_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('destination_account', sa.String(length=100), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('estimated_completion', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_requests_advisor_id'), 'payout_requests', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_payout_requests_client_id'), 'payout_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_payout_requests_id'), 'payout_requests', ['id'], unique=False)
    op.create_index(op.f('ix_payout_requests_payout_type'), 'payout_requests', ['payout_type'], unique=False)
    op.create_index(op.f('ix_payout_requests_status'), 'payout_requests', ['status'], unique=False)
    op.create_table('portfolio_admin_portfolios',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('portfolio_name', sa.String(length=255), nullable=False),
    sa.Column('portfolio_type', sa.String(length=100), nullable=True),
    sa.Column('base_currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('benchmark', sa.String(length=100), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('target_equity', sa.Float(), nullable=True),
    sa.Column('target_debt', sa.Float(), nullable=True),
    sa.Column('target_other', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_admin_portfolios_advisor_id'), 'portfolio_admin_portfolios', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_portfolios_client_id'), 'portfolio_admin_portfolios', ['client_id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_portfolios_id'), 'portfolio_admin_portfolios', ['id'], unique=False)
    op.create_table('revenue_records',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('revenue_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('revenue_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_records_id'), 'revenue_records', ['id'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_category', sa.String(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('questionnaire_version', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_profiles_id'), 'risk_profiles', ['id'], unique=False)
    op.create_table('sentiment_logs',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_logs_id'), 'sentiment_logs', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('voice_note_transcriptions',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_note_transcriptions_id'), 'voice_note_transcriptions', ['id'], unique=False)
    op.create_table('withdrawal_limits',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('daily_limit', sa.Float(), nullable=True),
    sa.Column('monthly_limit', sa.Float(), nullable=True),
    sa.Column('annual_limit', sa.Float(), nullable=True),
    sa.Column('requires_approval_above', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_limits_id'), 'withdrawal_limits', ['id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_entities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('messages_summarized', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_id'), 'conversation_summaries', ['id'], unique=False)
    op.create_table('funding_alerts',
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('funding_request_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['funding_request_id'], ['funding_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_alerts_advisor_id'), 'funding_alerts', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_funding_alerts_alert_type'), 'funding_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_funding_alerts_client_id'), 'funding_alerts', ['client_id'], unique=False)
    op.create_index(op.f('ix_funding_alerts_funding_request_id'), 'funding_alerts', ['funding_request_id'], unique=False)
    op.create_index(op.f('ix_funding_alerts_id'), 'funding_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_funding_alerts_is_resolved'), 'funding_alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_funding_alerts_severity'), 'funding_alerts', ['severity'], unique=False)
    op.create_table('funding_audit_log',
    sa.Column('funding_request_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funding_request_id'], ['funding_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_audit_log_action'), 'funding_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_funding_audit_log_advisor_id'), 'funding_audit_log', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_funding_audit_log_funding_request_id'), 'funding_audit_log', ['funding_request_id'], unique=False)
    op.create_index(op.f('ix_funding_audit_log_id'), 'funding_audit_log', ['id'], unique=False)
    op.create_table('funding_status_history',
    sa.Column('funding_request_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=True),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funding_request_id'], ['funding_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_status_history_funding_request_id'), 'funding_status_history', ['funding_request_id'], unique=False)
    op.create_index(op.f('ix_funding_status_history_id'), 'funding_status_history', ['id'], unique=False)
    op.create_table('funding_transactions',
    sa.Column('funding_request_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funding_request_id'], ['funding_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_transactions_advisor_id'), 'funding_transactions', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_funding_transactions_funding_request_id'), 'funding_transactions', ['funding_request_id'], unique=False)
    op.create_index(op.f('ix_funding_transactions_id'), 'funding_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_funding_transactions_reference_number'), 'funding_transactions', ['reference_number'], unique=True)
    op.create_index(op.f('ix_funding_transactions_status'), 'funding_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_funding_transactions_transaction_type'), 'funding_transactions', ['transaction_type'], unique=False)
    op.create_table('lead_activities',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_id'), 'lead_activities', ['id'], unique=False)
    op.create_table('lead_stage_history',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_stage_history_id'), 'lead_stage_history', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('payout_compliance_alerts',
    sa.Column('payout_request_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payout_request_id'], ['payout_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_compliance_alerts_advisor_id'), 'payout_compliance_alerts', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_payout_compliance_alerts_alert_type'), 'payout_compliance_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_payout_compliance_alerts_id'), 'payout_compliance_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_payout_compliance_alerts_is_resolved'), 'payout_compliance_alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_payout_compliance_alerts_payout_request_id'), 'payout_compliance_alerts', ['payout_request_id'], unique=False)
    op.create_index(op.f('ix_payout_compliance_alerts_severity'), 'payout_compliance_alerts', ['severity'], unique=False)
    op.create_table('payout_status_history',
    sa.Column('payout_request_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payout_request_id'], ['payout_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_status_history_id'), 'payout_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_payout_status_history_payout_request_id'), 'payout_status_history', ['payout_request_id'], unique=False)
    op.create_table('payout_transactions',
    sa.Column('payout_request_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payout_request_id'], ['payout_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_transactions_advisor_id'), 'payout_transactions', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_payout_transactions_id'), 'payout_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payout_transactions_payout_request_id'), 'payout_transactions', ['payout_request_id'], unique=False)
    op.create_index(op.f('ix_payout_transactions_reference_number'), 'payout_transactions', ['reference_number'], unique=True)
    op.create_index(op.f('ix_payout_transactions_status'), 'payout_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payout_transactions_transaction_type'), 'payout_transactions', ['transaction_type'], unique=False)
    op.create_table('portfolio_admin_accounts',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('custodian_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_admin_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_admin_accounts_advisor_id'), 'portfolio_admin_accounts', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_accounts_id'), 'portfolio_admin_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_accounts_portfolio_id'), 'portfolio_admin_accounts', ['portfolio_id'], unique=False)
    op.create_table('portfolio_admin_positions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('security_id', sa.String(length=100), nullable=True),
    sa.Column('security_type', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('average_cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('current_price', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('last_price_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_admin_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_admin_positions_advisor_id'), 'portfolio_admin_positions', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_positions_id'), 'portfolio_admin_positions', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_positions_portfolio_id'), 'portfolio_admin_positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_positions_security_id'), 'portfolio_admin_positions', ['security_id'], unique=False)
    op.create_table('risk_answers',
    sa.Column('risk_profile_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_profile_id'], ['risk_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_answers_id'), 'risk_answers', ['id'], unique=False)
    op.create_table('portfolio_admin_transactions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='executed', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_admin_portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['portfolio_admin_positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_admin_transactions_advisor_id'), 'portfolio_admin_transactions', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_transactions_id'), 'portfolio_admin_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_transactions_portfolio_id'), 'portfolio_admin_transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_admin_transactions_position_id'), 'portfolio_admin_transactions', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_admin_transactions_position_id'), table_name='portfolio_admin_transactions')
    op.drop_index(op.f('ix_portfolio_admin_transactions_portfolio_id'), table_name='portfolio_admin_transactions')
    op.drop_index(op.f('ix_portfolio_admin_transactions_id'), table_name='portfolio_admin_transactions')
    op.drop_index(op.f('ix_portfolio_admin_transactions_advisor_id'), table_name='portfolio_admin_transactions')
    op.drop_table('portfolio_admin_transactions')
    op.drop_index(op.f('ix_risk_answers_id'), table_name='risk_answers')
    op.drop_table('risk_answers')
    op.drop_index(op.f('ix_portfolio_admin_positions_security_id'), table_name='portfolio_admin_positions')
    op.drop_index(op.f('ix_portfolio_admin_positions_portfolio_id'), table_name='portfolio_admin_positions')
    op.drop_index(op.f('ix_portfolio_admin_positions_id'), table_name='portfolio_admin_positions')
    op.drop_index(op.f('ix_portfolio_admin_positions_advisor_id'), table_name='portfolio_admin_positions')
    op.drop_table('portfolio_admin_positions')
    op.drop_index(op.f('ix_portfolio_admin_accounts_portfolio_id'), table_name='portfolio_admin_accounts')
    op.drop_index(op.f('ix_portfolio_admin_accounts_id'), table_name='portfolio_admin_accounts')
    op.drop_index(op.f('ix_portfolio_admin_accounts_advisor_id'), table_name='portfolio_admin_accounts')
    op.drop_table('portfolio_admin_accounts')
    op.drop_index(op.f('ix_payout_transactions_transaction_type'), table_name='payout_transactions')
    op.drop_index(op.f('ix_payout_transactions_status'), table_name='payout_transactions')
    op.drop_index(op.f('ix_payout_transactions_reference_number'), table_name='payout_transactions')
    op.drop_index(op.f('ix_payout_transactions_payout_request_id'), table_name='payout_transactions')
    op.drop_index(op.f('ix_payout_transactions_id'), table_name='payout_transactions')
    op.drop_index(op.f('ix_payout_transactions_advisor_id'), table_name='payout_transactions')
    op.drop_table('payout_transactions')
    op.drop_index(op.f('ix_payout_status_history_payout_request_id'), table_name='payout_status_history')
    op.drop_index(op.f('ix_payout_status_history_id'), table_name='payout_status_history')
    op.drop_table('payout_status_history')
    op.drop_index(op.f('ix_payout_compliance_alerts_severity'), table_name='payout_compliance_alerts')
    op.drop_index(op.f('ix_payout_compliance_alerts_payout_request_id'), table_name='payout_compliance_alerts')
    op.drop_index(op.f('ix_payout_compliance_alerts_is_resolved'), table_name='payout_compliance_alerts')
    op.drop_index(op.f('ix_payout_compliance_alerts_id'), table_name='payout_compliance_alerts')
    op.drop_index(op.f('ix_payout_compliance_alerts_alert_type'), table_name='payout_compliance_alerts')
    op.drop_index(op.f('ix_payout_compliance_alerts_advisor_id'), table_name='payout_compliance_alerts')
    op.drop_table('payout_compliance_alerts')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_lead_stage_history_id'), table_name='lead_stage_history')
    op.drop_table('lead_stage_history')
    op.drop_index(op.f('ix_lead_activities_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_funding_transactions_transaction_type'), table_name='funding_transactions')
    op.drop_index(op.f('ix_funding_transactions_status'), table_name='funding_transactions')
    op.drop_index(op.f('ix_funding_transactions_reference_number'), table_name='funding_transactions')
    op.drop_index(op.f('ix_funding_transactions_id'), table_name='funding_transactions')
    op.drop_index(op.f('ix_funding_transactions_funding_request_id'), table_name='funding_transactions')
    op.drop_index(op.f('ix_funding_transactions_advisor_id'), table_name='funding_transactions')
    op.drop_table('funding_transactions')
    op.drop_index(op.f('ix_funding_status_history_id'), table_name='funding_status_history')
    op.drop_index(op.f('ix_funding_status_history_funding_request_id'), table_name='funding_status_history')
    op.drop_table('funding_status_history')
    op.drop_index(op.f('ix_funding_audit_log_id'), table_name='funding_audit_log')
    op.drop_index(op.f('ix_funding_audit_log_funding_request_id'), table_name='funding_audit_log')
    op.drop_index(op.f('ix_funding_audit_log_advisor_id'), table_name='funding_audit_log')
    op.drop_index(op.f('ix_funding_audit_log_action'), table_name='funding_audit_log')
    op.drop_table('funding_audit_log')
    op.drop_index(op.f('ix_funding_alerts_severity'), table_name='funding_alerts')
    op.drop_index(op.f('ix_funding_alerts_is_resolved'), table_name='funding_alerts')
    op.drop_index(op.f('ix_funding_alerts_id'), table_name='funding_alerts')
    op.drop_index(op.f('ix_funding_alerts_funding_request_id'), table_name='funding_alerts')
    op.drop_index(op.f('ix_funding_alerts_client_id'), table_name='funding_alerts')
    op.drop_index(op.f('ix_funding_alerts_alert_type'), table_name='funding_alerts')
    op.drop_index(op.f('ix_funding_alerts_advisor_id'), table_name='funding_alerts')
    op.drop_table('funding_alerts')
    op.drop_index(op.f('ix_conversation_summaries_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_withdrawal_limits_id'), table_name='withdrawal_limits')
    op.drop_table('withdrawal_limits')
    op.drop_index(op.f('ix_voice_note_transcriptions_id'), table_name='voice_note_transcriptions')
    op.drop_table('voice_note_transcriptions')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sentiment_logs_id'), table_name='sentiment_logs')
    op.drop_table('sentiment_logs')
    op.drop_index(op.f('ix_risk_profiles_id'), table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_index(op.f('ix_revenue_records_id'), table_name='revenue_records')
    op.drop_table('revenue_records')
    op.drop_index(op.f('ix_portfolio_admin_portfolios_id'), table_name='portfolio_admin_portfolios')
    op.drop_index(op.f('ix_portfolio_admin_portfolios_client_id'), table_name='portfolio_admin_portfolios')
    op.drop_index(op.f('ix_portfolio_admin_portfolios_advisor_id'), table_name='portfolio_admin_portfolios')
    op.drop_table('portfolio_admin_portfolios')
    op.drop_index(op.f('ix_payout_requests_status'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_payout_type'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_id'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_client_id'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_advisor_id'), table_name='payout_requests')
    op.drop_table('payout_requests')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_advisor_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_advisor_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_advisor_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_funding_requests_workflow_stage'), table_name='funding_requests')
    op.drop_index(op.f('ix_funding_requests_id'), table_name='funding_requests')
    op.drop_index(op.f('ix_funding_requests_funding_type'), table_name='funding_requests')
    op.drop_index(op.f('ix_funding_requests_client_id'), table_name='funding_requests')
    op.drop_index(op.f('ix_funding_requests_advisor_id'), table_name='funding_requests')
    op.drop_table('funding_requests')
    op.drop_index(op.f('ix_funding_accounts_id'), table_name='funding_accounts')
    op.drop_index(op.f('ix_funding_accounts_client_id'), table_name='funding_accounts')
    op.drop_index(op.f('ix_funding_accounts_advisor_id'), table_name='funding_accounts')
    op.drop_table('funding_accounts')
    op.drop_index(op.f('ix_corporate_action_alerts_id'), table_name='corporate_action_alerts')
    op.drop_table('corporate_action_alerts')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_compliance_alerts_id'), table_name='compliance_alerts')
    op.drop_table('compliance_alerts')
    op.drop_index(op.f('ix_communication_logs_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index(op.f('ix_commission_records_id'), table_name='commission_records')
    op.drop_table('commission_records')
    op.drop_index(op.f('ix_client_tags_id'), table_name='client_tags')
    op.drop_table('client_tags')
    op.drop_index(op.f('ix_client_reminders_id'), table_name='client_reminders')
    op.drop_table('client_reminders')
    op.drop_index(op.f('ix_client_notes_id'), table_name='client_notes')
    op.drop_table('client_notes')
    op.drop_index(op.f('ix_client_nominees_id'), table_name='client_nominees')
    op.drop_table('client_nominees')
    op.drop_index(op.f('ix_client_life_goals_id'), table_name='client_life_goals')
    op.drop_table('client_life_goals')
    op.drop_index(op.f('ix_client_family_members_id'), table_name='client_family_members')
    op.drop_table('client_family_members')
    op.drop_index(op.f('ix_client_engagement_scores_id'), table_name='client_engagement_scores')
    op.drop_table('client_engagement_scores')
    op.drop_index(op.f('ix_client_documents_id'), table_name='client_documents')
    op.drop_table('client_documents')
    op.drop_index(op.f('ix_client_corporate_actions_id'), table_name='client_corporate_actions')
    op.drop_table('client_corporate_actions')
    op.drop_index(op.f('ix_client_consents_id'), table_name='client_consents')
    op.drop_table('client_consents')
    op.drop_index(op.f('ix_client_aum_id'), table_name='client_aum')
    op.drop_table('client_aum')
    op.drop_index(op.f('ix_client_activities_id'), table_name='client_activities')
    op.drop_table('client_activities')
    op.drop_index(op.f('ix_churn_predictions_id'), table_name='churn_predictions')
    op.drop_table('churn_predictions')
    op.drop_index(op.f('ix_cash_balances_id'), table_name='cash_balances')
    op.drop_index(op.f('ix_cash_balances_client_id'), table_name='cash_balances')
    op.drop_index(op.f('ix_cash_balances_advisor_id'), table_name='cash_balances')
    op.drop_table('cash_balances')
    op.drop_index(op.f('ix_campaign_segments_id'), table_name='campaign_segments')
    op.drop_table('campaign_segments')
    op.drop_index(op.f('ix_campaign_recipients_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_campaign_message_logs_id'), table_name='campaign_message_logs')
    op.drop_table('campaign_message_logs')
    op.drop_index(op.f('ix_ai_meeting_summaries_id'), table_name='ai_meeting_summaries')
    op.drop_table('ai_meeting_summaries')
    op.drop_index(op.f('ix_advice_records_id'), table_name='advice_records')
    op.drop_table('advice_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_message_templates_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_corporate_actions_id'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_communication_campaigns_id'), table_name='communication_campaigns')
    op.drop_table('communication_campaigns')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
